module.exports = [
  "Whispering Pines",
  "Cedar Creek Retreat",
  "Sunset Valley Campground",
  "Mountain View Lodge",
  "Rustic River Camp",
  "Lakeside Haven",
  "Starlit Sky Camp",
  "Tranquil Trails",
  "Wildflower Meadows",
  "Forest Edge Campsite",
  "Sunny Hills Campground",
  "Canyon View Camp",
  "Crystal Lake Retreat",
  "Adventure Bay Campground",
  "Hidden Valley Campsites",
  "Echo Ridge Camp",
  "Nature's Embrace",
  "Pinecone Point",
  "Serenity Springs Campground",
  "Blue Sky Meadows",
  "Misty Mountain Retreat",
  "Golden Valley Camp",
  "Breezy Bluff Campground",
  "Riverbend Lodge",
  "Harmony Hill Camp",
  "Cypress Grove Campground",
  "Sunnyvale Retreat",
  "Secluded Springs",
  "Granite Peaks Camp",
  "Oak Hollow Campsite",
  "Timberline Lodge",
  "Emerald Bay Camp",
  "Winding River Retreat",
  "Whispering Winds Campground",
  "Blossom Hill Campsite",
  "Crisp Autumn Camp",
  "Rustling Leaves Retreat",
  "Canyon Crest Campground",
  "Mossy Rock Lodge",
  "Pine Ridge Retreat",
  "Sunrise Point Camp",
  "Trout Stream Camp",
  "Meadowlark Lodge",
  "Treetop Haven",
  "Lush Green Retreat",
  "Starry Night Campground",
  "Cool Breeze Camp",
  "Mountain Stream Lodge",
  "Riverstone Retreat",
  "Grove Hill Campground",
  "Open Sky Campsite",
  "Whimsical Woods",
  "Nature's Sanctuary",
  "Trailblazer Camp",
  "Woodland Retreat",
  "Sandy Shores Campground",
  "Fallen Leaves Lodge",
  "Stony Brook Camp",
  "Sierra Vista Campground",
  "Dreamer's Cove",
  "Hearthstone Camp",
  "Campfire Grove",
  "Bluebird Meadows",
  "Serene Summit Camp",
  "Alpine Escape Campground",
  "Hidden Gem Retreat",
  "Crystal Waters Lodge",
  "Driftwood Camp",
  "Birchwood Haven",
  "Wilderness Ridge Campground",
  "Charming Creek Campsite",
  "Rustic Escape",
  "Hilltop Haven",
  "Cedar Falls Camp",
  "Aspen Grove Retreat",
  "Sapphire Lake Campground",
  "Nature's Rest",
  "Canyon Springs Camp",
  "Sundown Campground",
  "Forest Haven Lodge",
  "River's Edge Retreat",
  "Sunset Ridge Camp",
  "Granite Falls Camp",
  "Pebble Beach Campground",
  "Woodland Glen Retreat",
  "Cypress Hill Camp",
  "Dewdrop Campground",
  "Mountain Hideaway",
  "Starview Retreat",
  "Whispering Brook Camp",
  "Pine Valley Lodge",
  "Green Pastures Campground",
  "Lost Valley Retreat",
  "Sunrise Meadows",
  "Mountain Crest Campground",
  "Serenity Woods Lodge",
  "Cedar Ridge Retreat",
  "Moonlit Grove Camp",
  "Pine Forest Campground",
  "Cloudy Bay Retreat",
  "Wildlife Watchers Camp",
  "Summer Breeze Campground",
  "Foggy Hills Lodge",
  "Daisy Meadow Retreat",
];
